name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    # To enable auto publishing to github, update your electron publisher
    # config in package.json > "build" and remove the conditional below
    if: ${{ github.repository_owner == 'JorrinKievit' }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Install Node and yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install and build
        run: |
          export TMDB_API_KEY=${{ secrets.TMDB_API_KEY }}
          export OPENSUBTITLES_API_KEY=${{ secrets.OPENSUBTITLES_API_KEY }}
          echo $TMDB_API_KEY
          echo $OPENSUBTITLES_API_KEY
          env TMDB_API_KEY=$TMDB_API_KEY OPENSUBTITLES_API_KEY=$OPENSUBTITLES_API_KEY yarn install
          env TMDB_API_KEY=$TMDB_API_KEY OPENSUBTITLES_API_KEY=$OPENSUBTITLES_API_KEY yarn run postinstall
          env TMDB_API_KEY=$TMDB_API_KEY OPENSUBTITLES_API_KEY=$OPENSUBTITLES_API_KEY yarn run build

      - name: Publish releases
        env:
          # These values are used for auto updates signing
          # APPLE_ID: ${{ secrets.APPLE_ID }}
          # APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
          # CSC_LINK: ${{ secrets.CSC_LINK }}
          # CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          # This is used for uploading release assets to github
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn exec electron-builder -- --publish always --win --mac --linux
